CREATE TABLE public.tb_secao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(50) NOT NULL,
	departamento_id bigint NOT NULL,
	CONSTRAINT secao_departamento_fk FOREIGN KEY (departamento_id) REFERENCES public.tb_departamento(id)
);
